<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/recipes_api.proto

namespace GPBMetadata\Api\V1;

class RecipesApi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Model\V1\Recipes::initOnce();
        $pool->internalAddGeneratedFile(
            '
‹
api/v1/recipes_api.protoapi.v1model/v1/recipes.proto"@
GetRecipesResponse*
recipes (2.model.v1.RecipeRrecipes"H
GetRecipesByAuthorResponse*
recipes (2.model.v1.RecipeRrecipes"Q
GetRecipesByAuthorRequest4
author (2.google.protobuf.StringValueRauthor"
GetRecipesRequest2³
ProtoApiServiceC

GetRecipes.api.v1.GetRecipesRequest.api.v1.GetRecipesResponse[
GetRecipesByAuthor!.api.v1.GetRecipesByAuthorRequest".api.v1.GetRecipesByAuthorResponseB
com.recipes.apiPÊrecipesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

