<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/v1/recipes.proto

namespace recipes;

use UnexpectedValueException;

/**
 * Protobuf type <code>model.v1.Difficulty</code>
 */
class Difficulty
{
    /**
     * Generated from protobuf enum <code>DIFFICULTY_EASY_UNSPECIFIED = 0;</code>
     */
    const DIFFICULTY_EASY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DIFFICULTY_MODERATED = 1;</code>
     */
    const DIFFICULTY_MODERATED = 1;
    /**
     * Generated from protobuf enum <code>DIFFICULTY_HARD = 2;</code>
     */
    const DIFFICULTY_HARD = 2;

    private static $valueToName = [
        self::DIFFICULTY_EASY_UNSPECIFIED => 'DIFFICULTY_EASY_UNSPECIFIED',
        self::DIFFICULTY_MODERATED => 'DIFFICULTY_MODERATED',
        self::DIFFICULTY_HARD => 'DIFFICULTY_HARD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

