<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/recipes_api.proto

namespace recipes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.v1.GetRecipesByAuthorRequest</code>
 */
class GetRecipesByAuthorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    protected $author = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $author
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\RecipesApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getAuthor()
    {
        return $this->author;
    }

    public function hasAuthor()
    {
        return isset($this->author);
    }

    public function clearAuthor()
    {
        unset($this->author);
    }

    /**
     * Returns the unboxed value from <code>getAuthor()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @return string|null
     */
    public function getAuthorUnwrapped()
    {
        return $this->readWrapperValue("author");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->author = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setAuthorUnwrapped($var)
    {
        $this->writeWrapperValue("author", $var);
        return $this;}

}

