<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/recipes_api.proto

namespace recipes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.v1.GetRecipesRequest</code>
 */
class GetRecipesRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\RecipesApi::initOnce();
        parent::__construct($data);
    }

}

