<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/recipes_api.proto

namespace recipes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>api.v1.GetRecipesResponse</code>
 */
class GetRecipesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    private $recipes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \recipes\Recipe[]|\Google\Protobuf\Internal\RepeatedField $recipes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\RecipesApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecipes()
    {
        return $this->recipes;
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     * @param \recipes\Recipe[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecipes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \recipes\Recipe::class);
        $this->recipes = $arr;

        return $this;
    }

}

