<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/v1/recipes.proto

namespace recipes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.v1.Recipe</code>
 */
class Recipe extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
     */
    protected $author = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
     */
    protected $description = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
     */
    protected $prep_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
     */
    protected $cook_time = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
     */
    protected $servings = null;
    /**
     * Generated from protobuf field <code>.model.v1.Difficulty difficulty = 9 [json_name = "difficulty"];</code>
     */
    protected $difficulty = 0;
    /**
     * Generated from protobuf field <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
     */
    private $ingredients;
    /**
     * Generated from protobuf field <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
     */
    private $steps;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
     */
    private $images;
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
     */
    protected $notes = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $name
     *     @type \Google\Protobuf\StringValue $author
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type \Google\Protobuf\StringValue $description
     *     @type \Google\Protobuf\Int32Value $prep_time
     *     @type \Google\Protobuf\UInt32Value $cook_time
     *     @type \Google\Protobuf\UInt32Value $servings
     *     @type int $difficulty
     *     @type \recipes\Ingredient[]|\Google\Protobuf\Internal\RepeatedField $ingredients
     *     @type \recipes\Step[]|\Google\Protobuf\Internal\RepeatedField $steps
     *     @type \Google\Protobuf\BytesValue[]|\Google\Protobuf\Internal\RepeatedField $images
     *     @type \Google\Protobuf\StringValue $notes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Model\V1\Recipes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getName()
    {
        return $this->name;
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Returns the unboxed value from <code>getName()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @return string|null
     */
    public function getNameUnwrapped()
    {
        return $this->readWrapperValue("name");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->name = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setNameUnwrapped($var)
    {
        $this->writeWrapperValue("name", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getAuthor()
    {
        return $this->author;
    }

    public function hasAuthor()
    {
        return isset($this->author);
    }

    public function clearAuthor()
    {
        unset($this->author);
    }

    /**
     * Returns the unboxed value from <code>getAuthor()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
     * @return string|null
     */
    public function getAuthorUnwrapped()
    {
        return $this->readWrapperValue("author");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->author = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setAuthorUnwrapped($var)
    {
        $this->writeWrapperValue("author", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Returns the unboxed value from <code>getDescription()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
     * @return string|null
     */
    public function getDescriptionUnwrapped()
    {
        return $this->readWrapperValue("description");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->description = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setDescriptionUnwrapped($var)
    {
        $this->writeWrapperValue("description", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
     * @return \Google\Protobuf\Int32Value|null
     */
    public function getPrepTime()
    {
        return $this->prep_time;
    }

    public function hasPrepTime()
    {
        return isset($this->prep_time);
    }

    public function clearPrepTime()
    {
        unset($this->prep_time);
    }

    /**
     * Returns the unboxed value from <code>getPrepTime()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
     * @return int|null
     */
    public function getPrepTimeUnwrapped()
    {
        return $this->readWrapperValue("prep_time");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setPrepTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->prep_time = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
     * @param int|null $var
     * @return $this
     */
    public function setPrepTimeUnwrapped($var)
    {
        $this->writeWrapperValue("prep_time", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
     * @return \Google\Protobuf\UInt32Value|null
     */
    public function getCookTime()
    {
        return $this->cook_time;
    }

    public function hasCookTime()
    {
        return isset($this->cook_time);
    }

    public function clearCookTime()
    {
        unset($this->cook_time);
    }

    /**
     * Returns the unboxed value from <code>getCookTime()</code>

     * Generated from protobuf field <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
     * @return int|null
     */
    public function getCookTimeUnwrapped()
    {
        return $this->readWrapperValue("cook_time");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
     * @param \Google\Protobuf\UInt32Value $var
     * @return $this
     */
    public function setCookTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt32Value::class);
        $this->cook_time = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt32Value object.

     * Generated from protobuf field <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
     * @param int|null $var
     * @return $this
     */
    public function setCookTimeUnwrapped($var)
    {
        $this->writeWrapperValue("cook_time", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
     * @return \Google\Protobuf\UInt32Value|null
     */
    public function getServings()
    {
        return $this->servings;
    }

    public function hasServings()
    {
        return isset($this->servings);
    }

    public function clearServings()
    {
        unset($this->servings);
    }

    /**
     * Returns the unboxed value from <code>getServings()</code>

     * Generated from protobuf field <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
     * @return int|null
     */
    public function getServingsUnwrapped()
    {
        return $this->readWrapperValue("servings");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
     * @param \Google\Protobuf\UInt32Value $var
     * @return $this
     */
    public function setServings($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\UInt32Value::class);
        $this->servings = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\UInt32Value object.

     * Generated from protobuf field <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
     * @param int|null $var
     * @return $this
     */
    public function setServingsUnwrapped($var)
    {
        $this->writeWrapperValue("servings", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.model.v1.Difficulty difficulty = 9 [json_name = "difficulty"];</code>
     * @return int
     */
    public function getDifficulty()
    {
        return $this->difficulty;
    }

    /**
     * Generated from protobuf field <code>.model.v1.Difficulty difficulty = 9 [json_name = "difficulty"];</code>
     * @param int $var
     * @return $this
     */
    public function setDifficulty($var)
    {
        GPBUtil::checkEnum($var, \recipes\Difficulty::class);
        $this->difficulty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIngredients()
    {
        return $this->ingredients;
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
     * @param \recipes\Ingredient[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIngredients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \recipes\Ingredient::class);
        $this->ingredients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSteps()
    {
        return $this->steps;
    }

    /**
     * Generated from protobuf field <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
     * @param \recipes\Step[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSteps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \recipes\Step::class);
        $this->steps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
     * @param \Google\Protobuf\BytesValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\BytesValue::class);
        $this->images = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getNotes()
    {
        return $this->notes;
    }

    public function hasNotes()
    {
        return isset($this->notes);
    }

    public function clearNotes()
    {
        unset($this->notes);
    }

    /**
     * Returns the unboxed value from <code>getNotes()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
     * @return string|null
     */
    public function getNotesUnwrapped()
    {
        return $this->readWrapperValue("notes");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setNotes($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->notes = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setNotesUnwrapped($var)
    {
        $this->writeWrapperValue("notes", $var);
        return $this;}

}

