<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/v1/recipes.proto

namespace recipes;

if (false) {
    /**
     * This class is deprecated. Use recipes\Unit\UnitOfMeasure instead.
     * @deprecated
     */
    class Unit_UnitOfMeasure {}
}
class_exists(Unit\UnitOfMeasure::class);
@trigger_error('recipes\Unit_UnitOfMeasure is deprecated and will be removed in the next major release. Use recipes\Unit\UnitOfMeasure instead', E_USER_DEPRECATED);

