<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/v1/recipes.proto

namespace recipes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.v1.Unit</code>
 */
class Unit extends \Google\Protobuf\Internal\Message
{
    protected $measure_unit;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $uom
     *     @type int $unit_of_measure
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Model\V1\Recipes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @return \Google\Protobuf\StringValue|null
     */
    public function getUom()
    {
        return $this->readOneof(1);
    }

    public function hasUom()
    {
        return $this->hasOneof(1);
    }

    /**
     * Returns the unboxed value from <code>getUom()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @return string|null
     */
    public function getUomUnwrapped()
    {
        return $this->readWrapperValue("uom");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setUom($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @param string|null $var
     * @return $this
     */
    public function setUomUnwrapped($var)
    {
        $this->writeWrapperValue("uom", $var);
        return $this;}

    /**
     * Generated from protobuf field <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @return int
     */
    public function getUnitOfMeasure()
    {
        return $this->readOneof(2);
    }

    public function hasUnitOfMeasure()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @param int $var
     * @return $this
     */
    public function setUnitOfMeasure($var)
    {
        GPBUtil::checkEnum($var, \recipes\Unit\UnitOfMeasure::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMeasureUnit()
    {
        return $this->whichOneof("measure_unit");
    }

}

